ctyamashita/photo-ronin

Gemfile.lock, app/models/list.rb, app/models/marker.rb, app/models/photo.rb, app/models/place.rb, app/models/review.rb, db/migrate/20220523053052_add_name_to_users.rb, db/migrate/20220523054004_create_places.rb, db/migrate/20220523054020_create_photos.rb, db/migrate/20220523073325_create_lists.rb, db/migrate/20220523074149_create_markers.rb, db/migrate/20220523074848_create_reviews.rb, db/schema.rb, test/models/list_test.rb, test/models/marker_test.rb, test/models/photo_test.rb, test/models/place_test.rb, test/models/review_test.rb
=> created models other than meta-data

app/models/meta_data.rb, db/migrate/20220523075054_create_meta_data.rb, db/migrate/20220523083153_add_focal_length_to_meta_data.rb, db/schema.rb, test/models/meta_datum_test.rb
=> added metadata model

db/migrate/20220523053052_add_name_to_users.rb, db/schema.rb
=> modified user columns

app/models/list.rb, app/models/marker.rb, app/models/photo.rb, app/models/user.rb
=> added association

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_style.scss, app/views/places/_place_card.html.erb, app/views/places/index.html.erb
=> card fixed

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_button.html.erb, app/views/shared/_menu.html.erb
=> Created button component

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_style.scss, app/views/devise/sessions/new.html.erb, app/views/lists/_place-card-list.html.erb, app/views/lists/show.html.erb, app/views/places/_place_card.html.erb, app/views/shared/_menu.html.erb, app/views/users/_list_card.html.erb, app/views/users/_user_list_card.html.erb, app/views/users/dashboard.html.erb, db/seeds.rb
Tried to make the grid and text size more responsive for many screen sizes.
Also adjusted the menu icons
=> Card style

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_menu.html.erb, app/views/shared/_navbar.html.erb
=> Small fixes

app/controllers/places_controller.rb, app/views/places/show.html.erb
I deleted swiper slide function to make it more simple.
=> deleted swiper-slide

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_style.scss, app/views/shared/_menu.html.erb, app/views/shared/_new_list.html.erb
=> Styled the new_list form

app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_style.scss, app/views/shared/_menu.html.erb
=> Created new search btn, and added hover effect

app/controllers/lists_controller.rb, app/views/lists/index.html.erb, app/views/places/_info_window.html.erb
added list index feature 
1. after adding list, redirect to user's wish list (dashboard)
2. added a lists index page (all of the users' lists) as index.html.erb 
3. modified one of the menu icons to lists index page (all of the users' lists), shinji did this actually
=> added list_index feature

app/assets/stylesheets/components/_card.scss, app/views/places/show.html.erb
Is it OK with this show-page? Put img in the same line.
=> Added styling in show page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/javascript/controllers/map_toggle_controller.js, app/views/places/index.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_place_card.html.erb
=> Added style to the button and center

app/controllers/places_controller.rb, app/views/places/_info_window.html.erb
Added place's pic and changed color of address to green. Is this OK?
=> Added pic in info window

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/views/places/_map.html.erb, app/views/shared/_place_card.html.erb
Map size and small style fixes
=> Map size adjusted to full screen

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/home.html.erb, app/views/places/_map.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_place_card.html.erb, app/views/shared/_search.html.erb
Now can go back to homepage when click on the places icon
=> Link to homepage fixed

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/javascript/controllers/map_toggle_controller.js, app/views/pages/home.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_search.html.erb
=> Fixed color of search input and changed homepage

app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_style.scss, app/views/places/show.html.erb, app/views/shared/_place_card.html.erb
=> Styled the showpage with map and review sections(hardcoded)

app/views/places/show.html.erb
https://user-images.githubusercontent.com/100399727/170413468-ee2a81b3-1c46-4725-bfd7-80faec5acbbf.mov
=> Created the carousel, but we need to implement the iteration

app/controllers/places_controller.rb, app/controllers/reviews_controller.rb, app/models/place.rb, app/policies/review_policy.rb, app/views/places/show.html.erb, config/routes.rb
I added review in html/ routes, def-create of controller.
=> Review page

app/assets/config/manifest.js, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_icon.scss, app/views/shared/_menu.html.erb
=> Fix menu add icon

app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/shared/_place_card.html.erb, db/seeds.rb
added recommended(hidden) and trending places without tags in the homepage
=> Real places

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_search.scss, app/views/places/_info_window.html.erb, app/views/places/show.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_new_place.html.erb
=> Adjusted: menu, info_card, some other minor styling

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_star_rating.scss, app/models/review.rb, app/views/places/show.html.erb
Did the review input, still have to display it.
=> made the stars input, can't display it

app/views/places/show.html.erb
Modified user name in review to display the user name who wrote a review.
=> user name in review fixed

app/views/places/show.html.erb
Changed rating star display to show the number of stars user reviewed.
=> changed the number of displaying review stars

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_search.scss, app/views/pages/home.html.erb, app/views/places/_info_window.html.erb, app/views/places/show.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_new_place.html.erb, app/views/shared/_place_card.html.erb
Let's check together the possible conflict
s
=> Fix homepage card

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_search.scss, app/views/shared/_new_list.html.erb, app/views/shared/_new_marker.html.erb
Full of gambiarra but seems to work.
=> Fix add list

app/views/places/show.html.erb, config/application.rb, config/locales/en.yml, test/test_helper.rb
Changed time display method for review.
=> Changed time display method for review

app/views/places/show.html.erb
Changed the styling of reviews.
=> Changed the styling for reviews

app/assets/stylesheets/components/_button.scss, app/javascript/controllers/map_toggle_controller.js, app/views/layouts/application.html.erb, app/views/places/_map.html.erb, app/views/places/index.html.erb
Also changed the button color to green, since our map is black now.
=> Search menu

app/controllers/application_controller.rb, app/models/place.rb, app/views/devise/registrations/new.html.erb
Added name form in the signup page.
=> added name in signup page

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_flashes.html.erb
=> Styled flashcards

app/views/places/show.html.erb
=> Inverted post a review and reviews.

Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
Added photo upload form for icon in sign-up page.
=> added photo upload form into signup page

app/assets/stylesheets/components/_avatar.scss, app/views/places/show.html.erb
Added icon in review but the underlines between each review are gone.
=> added icon in review

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_photo.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/components/_tag.scss, app/helpers/tag_helper.rb, app/views/places/_new_photo.html.erb, app/views/places/show.html.erb, app/views/shared/_place_card.html.erb
Fixed icon background and some other minor things.
Made the Add photo button smaller, not 100% satisfied yet.
=> Fix icon bg

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_photo.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/components/_tag.scss, app/helpers/tag_helper.rb, app/views/places/_new_photo.html.erb, app/views/places/show.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_place_card.html.erb
Changed icon for dashboard and removed icon names.
=> Menu adjust

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_photo.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/components/_tag.scss, app/helpers/tag_helper.rb, app/views/places/_new_photo.html.erb, app/views/places/show.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_place_card.html.erb
Organized the dashboard page and All lists page a bit different, removed the rating from the lists(we don't have it anyway)
=> List and dashboard

Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_style.scss, app/views/lists/_list_card.html.erb, app/views/lists/index.html.erb, app/views/places/show.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_new_marker.html.erb, app/views/users/_user_list_card.html.erb, app/views/users/dashboard.html.erb
Centered vertically and made the background full screen and a little transparent.
Cant fix that toggle button position(damn stimulus).
=> new list modal half-fixed

Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_style.scss, app/views/lists/_list_card.html.erb, app/views/lists/index.html.erb, app/views/places/show.html.erb, app/views/shared/_new_list.html.erb, app/views/shared/_new_marker.html.erb, app/views/shared/_new_place.html.erb, app/views/users/_user_list_card.html.erb, app/views/users/dashboard.html.erb
Added some labels to the input fields, it wasn't the most intuitive..
=> Add label add place

app/assets/stylesheets/components/_icon.scss, app/views/places/show.html.erb
=> Review time position

app/views/lists/show.html.erb
Changed to have current user position when user click start-path button and moves to google map page.
=> Added current position into google map url

app/controllers/pages_controller.rb, app/views/pages/home.html.erb
added real recommended and trending on homepage
=> added real recommended and trending on homepage

app/assets/stylesheets/components/_overflow.scss, app/assets/stylesheets/components/_style.scss, app/views/places/_map.html.erb
=> adjusted map size to fit the screen

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card_horizontal.scss, app/assets/stylesheets/components/_new_photo.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/components/_tag.scss, app/views/lists/show.html.erb, app/views/shared/_card_horizontal.html.erb, config/application.rb
=> Create list cards

db/seeds.rb
added seeds of 65 more places but without names and addresses
=> added seeds of 65 more places but without names and addresses

config/application.rb, db/seeds.rb
added random images & 2 tags each  for random places
=> added random images & 2 tags each  for random places

app/assets/config/manifest.js, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_grid.scss, app/controllers/photos_controller.rb, app/javascript/controllers/map_toggle_controller.js, app/views/pages/home.html.erb, app/views/places/index.html.erb, app/views/shared/_home_card.html.erb
=> changed the homepage

app/views/layouts/application.html.erb
=> changed title

app/views/shared/_home_card.html.erb, app/views/shared/_search.html.erb
made tag search better by enabling search just by clicking on the tags
=> search form shows selected tags

app/assets/stylesheets/components/_card.scss, app/views/places/_info_window_photo.html.erb
=> Small info window

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/components/_style.scss, app/views/places/_info_window_photo.html.erb, app/views/places/show.html.erb
=> Plus btn - Changed the position to the bottom, included "add to a list" and some opacity

app/assets/stylesheets/components/_form.scss, app/views/places/show.html.erb
=> switched position of review form and reviews

app/javascript/controllers/map_toggle_controller.js, app/views/places/_map.html.erb, app/views/places/index.html.erb
fixed mapcuoff by removing dnone in map_toggle_controller.js
=> fixed mapcuoff by removing dnone in map_toggle_controller.js

app/assets/config/manifest.js, app/assets/config/manifest.json.erb
=> fix manifest

app/assets/stylesheets/components/_position.scss, app/controllers/lists_controller.rb
=> fixed add-list-btn

app/assets/stylesheets/components/_alert.scss, app/javascript/controllers/alert_controller.js, app/views/layouts/application.html.erb, config/meta.yml
improved flash alert & fixed og:image error
=> improved flash alert & fixed og:image error

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tab.scss, app/views/pages/home.html.erb
=> changed pills to tabs

app/assets/stylesheets/components/_tag.scss, app/helpers/tag_helper.rb, app/views/shared/_search.html.erb
=> removed icons

app/assets/stylesheets/components/_card.scss, app/views/pages/home.html.erb, app/views/shared/_menu.html.erb
fixed tab and cards border radiuses
=> fixed tab and cards border radiuses

db/seeds.rb
Added seed for photos with tag.
=> photo seed created

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_style.scss, app/assets/stylesheets/components/_user.scss, app/views/lists/index.html.erb, app/views/places/show.html.erb
fixed border bottom and changed a bit on users page
=> fixed border bottom and changed a bit on users page

app/assets/stylesheets/components/_user.scss, app/views/lists/index.html.erb
=> added basic users page

app/assets/stylesheets/components/_style.scss, app/views/layouts/application.html.erb, app/views/shared/_new_place.html.erb
Just deleted one line from application.html.erb
=> trying to fix pwa

app/assets/stylesheets/components/_card.scss
shrinked image on map of show page
=> shrinked image on map of show page
